### ISSUE TITLE
Make Error(错误：隐式声明函数‘irq_data_to_desc’ )

### ISSUE THREAD

**Issue by lgzcoollg** [WCHSoftGroup/ch34x_mphsi_master_linux#2]
Help pls.

PS: I can't find any 'ira_data_to_desc' in my kernel through
grep -nr "irq_data_to_desc" /usr/src/kernels/

--------------ERROR.  PRINT-------------------

make -C /lib/modules/3.10.0-1160.95.1.el7.x86_64/build M=/root/ch34x_mphsi_master_linux-main/driver modules
make[1]: 进入目录“/usr/src/kernels/3.10.0-1160.95.1.el7.x86_64”
  CC [M]  /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.o
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.c: 在函数‘ch34x_usb_probe’中:
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.c:389:6: **警告：此函数中的‘ret’在使用前可能未初始化 [-Wmaybe-uninitialized]
  int ret;
      ^**
  CC [M]  /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.o
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c: 在函数‘ch347_spi_setup’中:
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:800:21: **警告：未使用的变量‘master’ [-Wunused-variable] **
  struct spi_master *master = spi->master;
                     ^
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:925:25: **警告：此函数中的‘clock_index’在使用前可能未初始化 [-Wmaybe-uninitialized]
   if (ch347spi_clockinit(ch34x_dev, clock_index) == false) { **
                         ^
In file included from include/linux/printk.h:242:0,
                 from include/linux/kernel.h:13,
                 from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi.h:10,
                 from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:15:
include/linux/dynamic_debug.h:86:20: 警告：此函数中的‘scale’在使用前可能未初始化 [-Wmaybe-uninitialized]
   __dynamic_dev_dbg(&descriptor, dev, fmt, \ 
                    ^
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:803:5: 附注：‘scale’在此声明
  u8 scale;
     ^
  CC [M]  /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_i2c.o
  CC [M]  /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.o
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c: 在函数‘ch347_irq_check’中:
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:143:2: **错误：隐式声明函数‘irq_data_to_desc’ [-Werror=implicit-function-declaration]
  handle_simple_irq(ch34x_dev->irq_base + irq, irq_data_to_desc(irq_get_irq_data(ch34x_dev->irq_base + irq)));
  ^**
/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:143:2: **警告：传递‘handle_simple_irq’的第 2 个参数时将整数赋给指针，未作类型转换 [默认启用]**
In file included from ./arch/x86/include/asm/hardirq.h:5:0,
                 from include/linux/hardirq.h:8,
                 from include/linux/interrupt.h:12,
                 from include/linux/usb.h:16,
                 from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi.h:15,
                 from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:15:
include/linux/irq.h:423:13: 附注：需要类型‘struct irq_desc *’，但实参的类型为‘int’
 extern void handle_simple_irq(unsigned int irq, struct irq_desc *desc);
             ^
cc1: some warnings being treated as errors
make[2]: *** [/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.o] 错误 1
make[1]: *** [_module_/root/ch34x_mphsi_master_linux-main/driver] 错误 2
make[1]: 离开目录“/usr/src/kernels/3.10.0-1160.95.1.el7.x86_64”
make: *** [modules] **错误 2**

--------------------------------------------

**EVN:**
uname -a
Linux CentOS 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

**Installed:**
kernel.x86_64                    3.10.0-1160.95.1.el7                  @updates 
kernel-devel.x86_64              3.10.0-1160.95.1.el7                  @updates 
kernel-headers.x86_64            3.10.0-1160.95.1.el7                  @updates 
kernel-tools.x86_64              3.10.0-1160.95.1.el7                  @updates 
kernel-tools-libs.x86_64         3.10.0-1160.95.1.el7                  @updates

**Comment by lgzcoollg** [comment]
似乎是gpio.c文件的140行，iqr_check函数对内核鉴别后，操作没有任何区别导致的。

```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 3, 0) 
         handle_simple_irq(irq_data_to_desc(irq_get_irq_data(ch34x_dev->irq_base + irq))); 
 #else 
         handle_simple_irq(ch34x_dev->irq_base + irq, irq_data_to_desc(irq_get_irq_data(ch34x_dev->irq_base + irq))); 
 #endif
```

我查到了一些资料:

![P30912-153827.jpg](https://github.com/WCHSoftGroup/ch34x_mphsi_master_linux/assets/48668011/27aeee1d-acda-4a9d-97ba-8f790e0a780a)

**Comment by WCHSoftGroup** [comment]
> Help pls.
> 
> PS: I can't find any 'ira_data_to_desc' in my kernel through grep -nr "irq_data_to_desc" /usr/src/kernels/
> 
> --------------ERROR. PRINT-------------------
> 
> make -C /lib/modules/3.10.0-1160.95.1.el7.x86_64/build M=/root/ch34x_mphsi_master_linux-main/driver modules make[1]: 进入目录“/usr/src/kernels/3.10.0-1160.95.1.el7.x86_64” CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.o /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.c: 在函数‘ch34x_usb_probe’中: /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.c:389:6: **警告：此函数中的‘ret’在使用前可能未初始化 [-Wmaybe-uninitialized] int ret; ^** CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.o /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c: 在函数‘ch347_spi_setup’中: /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:800:21: **警告：未使用的变量‘master’ [-Wunused-variable] ** struct spi_master *master = spi->master; ^ /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:925:25: **警告：此函数中的‘clock_index’在使用前可能未初始化 [-Wmaybe-uninitialized] if (ch347spi_clockinit(ch34x_dev, clock_index) == false) { ** ^ In file included from include/linux/printk.h:242:0, from include/linux/kernel.h:13, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi.h:10, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:15: include/linux/dynamic_debug.h:86:20: 警告：此函数中的‘scale’在使用前可能未初始化 [-Wmaybe-uninitialized] __dynamic_dev_dbg(&descriptor, dev, fmt, \ ^ /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:803:5: 附注：‘scale’在此声明 u8 scale; ^ CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_i2c.o CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.o /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c: 在函数‘ch347_irq_check’中: /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:143:2: **错误：隐式声明函数‘irq_data_to_desc’ [-Werror=implicit-function-declaration] handle_simple_irq(ch34x_dev->irq_base + irq, irq_data_to_desc(irq_get_irq_data(ch34x_dev->irq_base + irq))); ^** /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:143:2: **警告：传递‘handle_simple_irq’的第 2 个参数时将整数赋给指针，未作类型转换 [默认启用]** In file included from ./arch/x86/include/asm/hardirq.h:5:0, from include/linux/hardirq.h:8, from include/linux/interrupt.h:12, from include/linux/usb.h:16, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi.h:15, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:15: include/linux/irq.h:423:13: 附注：需要类型‘struct irq_desc *’，但实参的类型为‘int’ extern void handle_simple_irq(unsigned int irq, struct irq_desc *desc); ^ cc1: some warnings being treated as errors make[2]: *** [/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.o] 错误 1 make[1]: *** [_module_/root/ch34x_mphsi_master_linux-main/driver] 错误 2 make[1]: 离开目录“/usr/src/kernels/3.10.0-1160.95.1.el7.x86_64” make: *** [modules] **错误 2**
> 
> **EVN:** uname -a Linux CentOS 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> gcc -v 使用内建 specs。 COLLECT_GCC=gcc COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper 目标：x86_64-redhat-linux 配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux 线程模型：posix gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> 
> **Installed:** kernel.x86_64 3.10.0-1160.95.1.el7 @updates kernel-devel.x86_64 3.10.0-1160.95.1.el7 @updates kernel-headers.x86_64 3.10.0-1160.95.1.el7 @updates kernel-tools.x86_64 3.10.0-1160.95.1.el7 @updates kernel-tools-libs.x86_64 3.10.0-1160.95.1.el7 @updates

您好， 上面的问题提示是因为编译的时候提示：irq_data_to_desc 未定义。
事实上，3.10.0 内核API函数已经定制了该函数，链接：https://elixir.bootlin.com/linux/v3.10/source/kernel/irq/internals.h 
你可以尝试主动包含该文件，或者直接在 ch34x_mphsi.h 文件中定义下这个：

#define irq_data_to_desc(data)	container_of(data, struct irq_desc, irq_data)

**Comment by lgzcoollg** [comment]
> > Help pls.
> > PS: I can't find any 'ira_data_to_desc' in my kernel through grep -nr "irq_data_to_desc" /usr/src/kernels/
> > --------------ERROR. PRINT-------------------
> > make -C /lib/modules/3.10.0-1160.95.1.el7.x86_64/build M=/root/ch34x_mphsi_master_linux-main/driver modules make[1]: 进入目录“/usr/src/kernels/3.10.0-1160.95.1.el7.x86_64” CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.o /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.c: 在函数‘ch34x_usb_probe’中: /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_usb.c:389:6: **警告：此函数中的‘ret’在使用前可能未初始化 [-Wmaybe-uninitialized] int ret; ^** CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.o /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c: 在函数‘ch347_spi_setup’中: /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:800:21: **警告：未使用的变量‘master’ [-Wunused-variable] ** struct spi_master *master = spi->master; ^ /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:925:25: **警告：此函数中的‘clock_index’在使用前可能未初始化 [-Wmaybe-uninitialized] if (ch347spi_clockinit(ch34x_dev, clock_index) == false) { ** ^ In file included from include/linux/printk.h:242:0, from include/linux/kernel.h:13, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi.h:10, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:15: include/linux/dynamic_debug.h:86:20: 警告：此函数中的‘scale’在使用前可能未初始化 [-Wmaybe-uninitialized] __dynamic_dev_dbg(&descriptor, dev, fmt, \ ^ /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_spi.c:803:5: 附注：‘scale’在此声明 u8 scale; ^ CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_i2c.o CC [M] /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.o /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c: 在函数‘ch347_irq_check’中: /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:143:2: **错误：隐式声明函数‘irq_data_to_desc’ [-Werror=implicit-function-declaration] handle_simple_irq(ch34x_dev->irq_base + irq, irq_data_to_desc(irq_get_irq_data(ch34x_dev->irq_base + irq))); ^** /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:143:2: **警告：传递‘handle_simple_irq’的第 2 个参数时将整数赋给指针，未作类型转换 [默认启用]** In file included from ./arch/x86/include/asm/hardirq.h:5:0, from include/linux/hardirq.h:8, from include/linux/interrupt.h:12, from include/linux/usb.h:16, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi.h:15, from /root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.c:15: include/linux/irq.h:423:13: 附注：需要类型‘struct irq_desc *’，但实参的类型为‘int’ extern void handle_simple_irq(unsigned int irq, struct irq_desc *desc); ^ cc1: some warnings being treated as errors make[2]: *** [/root/ch34x_mphsi_master_linux-main/driver/ch34x_mphsi_master_gpio.o] 错误 1 make[1]: *** [_module_/root/ch34x_mphsi_master_linux-main/driver] 错误 2 make[1]: 离开目录“/usr/src/kernels/3.10.0-1160.95.1.el7.x86_64” make: *** [modules] **错误 2**
> > **EVN:** uname -a Linux CentOS 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> > gcc -v 使用内建 specs。 COLLECT_GCC=gcc COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper 目标：x86_64-redhat-linux 配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux 线程模型：posix gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
> > **Installed:** kernel.x86_64 3.10.0-1160.95.1.el7 @updates kernel-devel.x86_64 3.10.0-1160.95.1.el7 @updates kernel-headers.x86_64 3.10.0-1160.95.1.el7 @updates kernel-tools.x86_64 3.10.0-1160.95.1.el7 @updates kernel-tools-libs.x86_64 3.10.0-1160.95.1.el7 @updates
> 
> 您好， 上面的问题提示是因为编译的时候提示：irq_data_to_desc 未定义。 事实上，3.10.0 内核API函数已经定制了该函数，链接：https://elixir.bootlin.com/linux/v3.10/source/kernel/irq/internals.h 你可以尝试主动包含该文件，或者直接在 ch34x_mphsi.h 文件中定义下这个：
> 
> #define irq_data_to_desc(data) container_of(data, struct irq_desc, irq_data)

---------------------------------------
是的，我有查过内核本应该包含的，但是我的系统环境没有internals.h，在其它文件也查不到函数，
如我开头写的：grep -nr "irq_data_to_desc" /usr/src/kernels/是无输出的。

----------------------------------------
其实我把ch34x_mphsi_gpio.c的143行中irq_data_to_desc改为irq_to_desc，驱动也能make和运转，但是我认为是不对的（因为我从i2cdump数据似乎有点异常）。

**我没有下载一个internals.h放入到内核并包含到ch34x_mphsi.h中，我将按照第2个方法进行测试。**
结果：驱动也能make和运转。

--------
我认为可以关闭问题，谢谢

**Comment by WCHSoftGroup** [comment]
好的，后续有问题可以再单独发issue~
